apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: zeben-cl
  namespace: kafka  
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      plain: {}
      external:
        type: ingress
        authentication:
          type: tls
        configuration:
          bootstrap:
            # Example for local (minikube) and the nip.io service
            host: bootstrap.172.101.0.10.nip.io
          brokers:
          - broker: 0
            # Example for local (minikube) and the nip.io service
            host: broker-0.172.101.0.10.nip.io
          - broker: 1
            # Example for local (minikube) and the nip.io service
            host: broker-1.172.101.0.10.nip.io
          - broker: 2
            # Example for local (minikube) and the nip.io service
            host: broker-2.172.101.0.10.nip.io
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
    storage:
      type: persistent-claim
      size: 100Mi
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Mi
      deleteClaim: false      
  entityOperator:
    topicOperator: {}
    userOperator: {}
  clusterCa:
    generateCertificateAuthority: true
    # 5 years
    validityDays: 1825
    # certificate renewal before the old CA certificates expire
    renewalDays: 31
  clientsCa:
    generateCertificateAuthority: true
    # 5 years
    validityDays: 1825
    # Days certificate renewal before the old CA certificates expire
    renewalDays: 31  
