apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: zeben-cl
  namespace: kafka  
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      plain: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
    storage:
      type: persistent-claim
      size: 100Mi
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Mi
      deleteClaim: false      
  entityOperator:
    topicOperator: {}
    userOperator: {}